version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
      - "1881:1881"
    networks:
      - iot-platform
    volumes:
      - nodered-storage:/data

volumes:
  nodered-storage:

networks:
  iot-platform:
